from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel

class Audience(BaseModel):
    # Basic Information
    AudienceId: Optional[str] = None
    AudienceName: Optional[str] = None
    AdvertiserId: Optional[str] = None
    Description: Optional[str] = None
    
    # Data Group Targeting
    IncludedDataGroupIds: Optional[List[str]] = None
    ExcludedDataGroupIds: Optional[List[str]] = None
    
    # Counts and Metrics
    UniqueUserCount: Optional[int] = None
    WebCount: Optional[int] = None
    InAppCount: Optional[int] = None
    CtvCount: Optional[int] = None
    HouseholdCount: Optional[int] = None
    PersonsCount: Optional[int] = None
    
    # Status and Metadata
    IsAutoGenerated: Optional[bool] = None
    LastUpdatedAtUtc: Optional[datetime] = None
    ActiveIdsCountExpanded: Optional[bool] = None
    SuccessfullyRetrievedCounts: Optional[bool] = None
    
    # Geographic Settings
    GeoForCounts: Optional[str] = None