
from enum import Enum

class BidListSource(Enum):
    """
    None
    """
    FREQUENCY_MIGRATION = "FREQUENCY_MIGRATION"
    SYSTEM_AUTO = "SYSTEM_AUTO"
    SYSTEM_AUTO_FOR_ALWAYS_ON_DEALS = "SYSTEM_AUTO_FOR_ALWAYS_ON_DEALS"
    SYSTEM_AUTO_FOR_COMMITMENT_PRIORITIZATION = "SYSTEM_AUTO_FOR_COMMITMENT_PRIORITIZATION"
    SYSTEM_AUTO_FOR_COOKIE_LESS = "SYSTEM_AUTO_FOR_COOKIE_LESS"
    SYSTEM_AUTO_FOR_MARKETPLACE = "SYSTEM_AUTO_FOR_MARKETPLACE"
    SYSTEM_AUTO_FOR_WIN_RATE_EXCLUSION = "SYSTEM_AUTO_FOR_WIN_RATE_EXCLUSION"
    SYSTEM_MANUAL = "SYSTEM_MANUAL"
    USER = "USER"
    USER_BULK_EDIT = "USER_BULK_EDIT"
