
from enum import Enum

class Browser(Enum):
    """
    None
    """
    BAIDU = "BAIDU"
    CHROME = "CHROME"
    EDGE = "EDGE"
    FIREFOX = "FIREFOX"
    IN_APP = "IN_APP"
    INTERNET_EXPLORER10 = "INTERNET_EXPLORER10"
    INTERNET_EXPLORER11 = "INTERNET_EXPLORER11"
    INTERNET_EXPLORER7 = "INTERNET_EXPLORER7"
    INTERNET_EXPLORER8 = "INTERNET_EXPLORER8"
    INTERNET_EXPLORER9 = "INTERNET_EXPLORER9"
    OPERA = "OPERA"
    OTHER = "OTHER"
    SAFARI = "SAFARI"
    WEB_VIEW = "WEB_VIEW"
    YANDEX = "YANDEX"
