
from enum import Enum

class CampaignCloneInventoryRecommendationType(Enum):
    """
    Inventory settings for an ad group on the context of Campaign Clone.
    """
    NO_UPGRADE = "NO_UPGRADE"
    UPGRADE_MARKETPLACE = "UPGRADE_MARKETPLACE"
    UPGRADE_MARKETPLACE_FROM_OPENMARKET = "UPGRADE_MARKETPLACE_FROM_OPENMARKET"
    UPGRADE_MARKETPLACE_FROM_PRIVATECONTRACTS = "UPGRADE_MARKETPLACE_FROM_PRIVATECONTRACTS"
    UPGRADE_MARKETPLACE_LIMITED_TO_PROPERTIES = "UPGRADE_MARKETPLACE_LIMITED_TO_PROPERTIES"
