
from enum import Enum

class CreativeAuditStatus(Enum):
    """
    None
    """
    APPROVED = "APPROVED"
    CONDITIONALLY_APPROVED = "CONDITIONALLY_APPROVED"
    ESCALATED = "ESCALATED"
    LIMITED = "LIMITED"
    MIGRATING_NEW_MEMBER_ID = "MIGRATING_NEW_MEMBER_ID"
    NOT_AUDITED = "NOT_AUDITED"
    NOT_FOUND = "NOT_FOUND"
    PARTIALLY_APPROVED = "PARTIALLY_APPROVED"
    PENDING = "PENDING"
    PENDING_COPY_TO_CN = "PENDING_COPY_TO_CN"
    REJECTED = "REJECTED"
    TIME_DELAYED_APPROVED = "TIME_DELAYED_APPROVED"
    TIME_DELAYED_REJECT = "TIME_DELAYED_REJECT"
    UNAUDITABLE = "UNAUDITABLE"
    UNKNOWN = "UNKNOWN"
