
from enum import Enum

class CreativeTagType(Enum):
    """
    None
    """
    APPLE_I_AD = "APPLE_I_AD"
    BROADCASTER_HOSTED_VIDEO = "BROADCASTER_HOSTED_VIDEO"
    FLASH = "FLASH"
    HOSTED = "HOSTED"
    HOSTED_AUDIO = "HOSTED_AUDIO"
    HOSTED_NATIVE = "HOSTED_NATIVE"
    HOSTED_NATIVE_VIDEO = "HOSTED_NATIVE_VIDEO"
    HOSTED_NATIVE_WITH_THIRD_PARTY_VIDEO = "HOSTED_NATIVE_WITH_THIRD_PARTY_VIDEO"
    HOSTED_VIDEO = "HOSTED_VIDEO"
    NONE = "NONE"
    PUBLISHER_HOSTED = "PUBLISHER_HOSTED"
    THIRD_PARTY = "THIRD_PARTY"
    THIRD_PARTY_AUDIO = "THIRD_PARTY_AUDIO"
    THIRD_PARTY_NATIVE = "THIRD_PARTY_NATIVE"
    THIRD_PARTY_NATIVE_VIDEO = "THIRD_PARTY_NATIVE_VIDEO"
    THIRD_PARTY_VIDEO = "THIRD_PARTY_VIDEO"
    THIRD_PARTY_VIDEO_BY_TOKEN = "THIRD_PARTY_VIDEO_BY_TOKEN"
