
from enum import Enum

class CustomROASType(Enum):
    """
    None
    """
    CLICK_VIEWTHROUGH_WEIGHTING = "CLICK_VIEWTHROUGH_WEIGHTING"
    COMPOSITE_WEIGHTING = "COMPOSITE_WEIGHTING"
    DISABLED = "DISABLED"
    PIXEL_WEIGHTING = "PIXEL_WEIGHTING"
