
from enum import Enum

class EncodingIssueCode(Enum):
    """
    None
    """
    INCORRECT_BITRATE = "INCORRECT_BITRATE"
    INCORRECT_FILE_SIZE = "INCORRECT_FILE_SIZE"
    INCORRECT_FILE_TYPE = "INCORRECT_FILE_TYPE"
    INCORRECT_RESOLUTION = "INCORRECT_RESOLUTION"
    RECOMMENDED_BITRATE = "RECOMMENDED_BITRATE"
