
from enum import Enum

class FeeType(Enum):
    """
    None
    """
    CPC = "CPC"
    CPM = "CPM"
    DATA_COST_PERCENTAGE = "DATA_COST_PERCENTAGE"
    FEE_BASIS_PERCENTAGE = "FEE_BASIS_PERCENTAGE"
    MEDIA_COST_PERCENTAGE = "MEDIA_COST_PERCENTAGE"
    NONE = "NONE"
    VARIABLE_COST_PERCENTAGE = "VARIABLE_COST_PERCENTAGE"
