
from enum import Enum

class FrequencyCounterSpecialType(Enum):
    """
    Special type for FrequencyCounter. Default is None.
    """
    CROSS_DSP = "CROSS_DSP"
    MODEL = "MODEL"
    NONE = "NONE"
    OMNICHANNEL_RETARGETING = "OMNICHANNEL_RETARGETING"
    REACH = "REACH"
    RESTRICTED_AD_GROUP = "RESTRICTED_AD_GROUP"
    RESTRICTED_CAMPAIGN_INTERVAL = "RESTRICTED_CAMPAIGN_INTERVAL"
    RESTRICTED_CAMPAIGN_LIFETIME = "RESTRICTED_CAMPAIGN_LIFETIME"
    RESTRICTED_FREQUENCY_GROUP = "RESTRICTED_FREQUENCY_GROUP"
    UI_GROUP = "UI_GROUP"
