
from enum import Enum

class InternetConnectionType(Enum):
    """
    None
    """
    CELLULAR_NETWORK_UNKNOWN = "CELLULAR_NETWORK_UNKNOWN"
    CELLULAR_NETWORK2_G = "CELLULAR_NETWORK2_G"
    CELLULAR_NETWORK3_G = "CELLULAR_NETWORK3_G"
    CELLULAR_NETWORK4_G = "CELLULAR_NETWORK4_G"
    CELLULAR_NETWORK5_G = "CELLULAR_NETWORK5_G"
    ETHERNET = "ETHERNET"
    UNKNOWN = "UNKNOWN"
    WI_FI = "WI_FI"
