
from enum import Enum

class MultipleMatchResolutionType(Enum):
    """
    None
    """
    APPLY_AVERAGE_ADJUSTMENT = "APPLY_AVERAGE_ADJUSTMENT"
    APPLY_MAXIMUM_ADJUSTMENT = "APPLY_MAXIMUM_ADJUSTMENT"
    APPLY_MINIMUM_ADJUSTMENT = "APPLY_MINIMUM_ADJUSTMENT"
    APPLY_MULTIPLY_ADJUSTMENT = "APPLY_MULTIPLY_ADJUSTMENT"
    SINGLE_MATCH_ONLY = "SINGLE_MATCH_ONLY"
