
from enum import Enum

class NativeContextType(Enum):
    """
    None
    """
    APPLICATION_STORE = "APPLICATION_STORE"
    ARTICLE = "ARTICLE"
    AUDIO = "AUDIO"
    CHAT_OR_IM = "CHAT_OR_IM"
    CONTENT = "CONTENT"
    CONTENT_UNCLASSIFIED = "CONTENT_UNCLASSIFIED"
    EMAIL = "EMAIL"
    GENERAL = "GENERAL"
    GENERAL_SOCIAL = "GENERAL_SOCIAL"
    IMAGE = "IMAGE"
    PRODUCT = "PRODUCT"
    PRODUCT_REVIEW = "PRODUCT_REVIEW"
    PRODUCT_UNCLASSIFIED = "PRODUCT_UNCLASSIFIED"
    SELLING_PRODUCTS = "SELLING_PRODUCTS"
    SOCIAL = "SOCIAL"
    SOCIAL_UNCLASSIFIED = "SOCIAL_UNCLASSIFIED"
    UNCLASSIFIED = "UNCLASSIFIED"
    USER_GENERATED = "USER_GENERATED"
    VIDEO = "VIDEO"
