
from enum import Enum

class OmnichannelForecastRecommendationBasisType(Enum):
    """
    None
    """
    CONVERSION_RATE_INCREASE = "CONVERSION_RATE_INCREASE"
    INCREMENTAL_RETURN_ON_AD_SPEND_RATIO_INCREASE = "INCREMENTAL_RETURN_ON_AD_SPEND_RATIO_INCREASE"
    TIME_TO_CONVERSION_DECREASE = "TIME_TO_CONVERSION_DECREASE"
