
from enum import Enum

class PassThroughFeeType(Enum):
    """
    None
    """
    CUSTOM_PMP_PARTNER_DATA_COST_PERCENTAGE = "CUSTOM_PMP_PARTNER_DATA_COST_PERCENTAGE"
    DATA_COST_PERCENTAGE = "DATA_COST_PERCENTAGE"
    FEE_CPM = "FEE_CPM"
    MEDIA_COST_PERCENTAGE = "MEDIA_COST_PERCENTAGE"
    MEDIA_PLUS_DATA_COST_PERCENTAGE = "MEDIA_PLUS_DATA_COST_PERCENTAGE"
    NONE = "NONE"
    PARTNER_DATA_COST_PERCENTAGE = "PARTNER_DATA_COST_PERCENTAGE"
    RATE_CPC = "RATE_CPC"
    RATE_CPM = "RATE_CPM"
