
from enum import Enum

class QualityAllianceViewabilityProfileType(Enum):
    """
    None
    """
    DISPLAY_FULL_IN_VIEW2_SEC_VIDEO_FULL_IN_VIEW_HALF_DUR = "DISPLAY_FULL_IN_VIEW2_SEC_VIDEO_FULL_IN_VIEW_HALF_DUR"
    DISPLAY70_IN_VIEW2_SEC_VIDEO70_IN_VIEW5_SEC = "DISPLAY70_IN_VIEW2_SEC_VIDEO70_IN_VIEW5_SEC"
    DISPLAY70_IN_VIEW3_SEC_VIDEO80_IN_VIEW10_SEC = "DISPLAY70_IN_VIEW3_SEC_VIDEO80_IN_VIEW10_SEC"
    FULLY_IN_VIEW2_SECONDS = "FULLY_IN_VIEW2_SECONDS"
    GROUP_M = "GROUP_M"
    GROUP_MV2 = "GROUP_MV2"
    IAB = "IAB"
    IAS_DISPLAY75_IN_VIEW1_SEC = "IAS_DISPLAY75_IN_VIEW1_SEC"
    NESTLE = "NESTLE"
    PUBLICIS = "PUBLICIS"
    VOLKSWAGEN = "VOLKSWAGEN"
