
from enum import Enum

class ROIGoalType(Enum):
    """
    ROI goal type or category.
    """
    BROADCAST_AUDIENCE_SIZE = "BROADCAST_AUDIENCE_SIZE"
    BROADCAST_GRP = "BROADCAST_GRP"
    BROADCAST_TRP = "BROADCAST_TRP"
    CPA = "CPA"
    CPC = "CPC"
    CPCV = "CPCV"
    CROSSIX_AUDIENCE_QUALITY_INDEX = "CROSSIX_AUDIENCE_QUALITY_INDEX"
    CTR = "CTR"
    GRP = "GRP"
    IQVIA_AUDIENCE_QUALITY_INDEX = "IQVIA_AUDIENCE_QUALITY_INDEX"
    IQVIA_AUDIENCE_QUALITY_INDEX_AND_COST_PER_TARGET = "IQVIA_AUDIENCE_QUALITY_INDEX_AND_COST_PER_TARGET"
    LINEAR_TV_INCREMENTAL_REACH = "LINEAR_TV_INCREMENTAL_REACH"
    MIAOZHEN_OTP = "MIAOZHEN_OTP"
    NIELSEN_OTP = "NIELSEN_OTP"
    NO_GOAL = "NO_GOAL"
    NONE = "NONE"
    REACH = "REACH"
    ROAS = "ROAS"
    VCPM = "VCPM"
    VCR = "VCR"
    VIEWABILITY = "VIEWABILITY"
