from dataclasses import dataclass

@dataclass
class UserGroup:
    """
    None
    """
    description: str
    id: str
    isAutoGenerated: bool
    isProductEngineering: bool
    isTTDUser: bool
    name: str
    partnerGroupId: str
    partnerId: str
