
from enum import Enum

class VastErrorCode(Enum):
    """
    None
    """
    DURATION_OUT_OF_RANGE = "DURATION_OUT_OF_RANGE"
    NO_DURATION = "NO_DURATION"
    NO_MEDIA_FILES = "NO_MEDIA_FILES"
    NO_SUPPORTED_NESTED_VPAID_MEDIA_FILE = "NO_SUPPORTED_NESTED_VPAID_MEDIA_FILE"
    VAST_VALIDATION_ERROR = "VAST_VALIDATION_ERROR"
